helloMessage: "Hello H2!"

spring:
  datasource:
    url: jdbc:mysql://18.143.180.121:3306/jpoc?useSSL=false&serverTimezone=Asia/Singapore
    username: admin
    password: 123456
  jpa:
    hibernate:
      ddl-validate: validate # none, validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect