server:
  port: 8081

spring:
  profiles:
    default: mysql
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

logging:
  level:
    root: ERROR
    org.springframework: INFO
    com.ganjp.jpoc: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: "jpoc-springboot-restful-api.log"